<Project>
  <PropertyGroup>
    <ImplicitUsings>enable</ImplicitUsings><Nullable>enable</Nullable><LangVersion>14</LangVersion>
    <Version>0.1.0-alpha.1</Version><Authors>Wiesław Šoltés; TextSpace contributors</Authors>
    <Company>TextSpace</Company><Copyright>Copyright © 2026 TextSpace contributors</Copyright>
    <RepositoryUrl>https://github.com/wieslawsoltes/TextSpace</RepositoryUrl><RepositoryType>git</RepositoryType>
    <PackageProjectUrl>https://github.com/wieslawsoltes/TextSpace</PackageProjectUrl>
    <PackageLicenseExpression>MIT</PackageLicenseExpression><PackageReadmeFile>README.md</PackageReadmeFile>
    <IncludeSymbols>true</IncludeSymbols><SymbolPackageFormat>snupkg</SymbolPackageFormat>
    <PublishRepositoryUrl>true</PublishRepositoryUrl><EmbedUntrackedSources>true</EmbedUntrackedSources>
    <Deterministic>true</Deterministic><ContinuousIntegrationBuild Condition="'$(CI)' == 'true'">true</ContinuousIntegrationBuild>
    <JsonSerializerIsReflectionEnabledByDefault>true</JsonSerializerIsReflectionEnabledByDefault>
  </PropertyGroup>
  <ItemGroup><None Include="$(MSBuildThisFileDirectory)README.md" Pack="true" PackagePath="/" Visible="false" /></ItemGroup>
</Project>
