from pathlib import Path

def replace(path, old, new):
    path = Path(path)
    text = path.read_text()
    assert text.count(old) == 1, (str(path), old)
    path.write_text(text.replace(old, new, 1))

replace('src/TextSpace.Layout/PageLayoutEngine.cs', 'public sealed class PageLayoutEngine(ITextMetrics metrics)\n{', 'public sealed class PageLayoutEngine(ITextMetrics metrics)\n{\n    public ParagraphLayoutCache ParagraphCache { get; } = new(metrics);')
replace('src/TextSpace.Layout/PageLayoutEngine.cs', 'var layouter = new ParagraphLayouter(metrics);', 'var layouter = ParagraphCache;')
replace('src/TextSpace.Skia/SkiaTextMetrics.cs', 'public sealed class SkiaTextMetrics : ITextMetrics, IDisposable', 'public sealed class SkiaTextMetrics : IVersionedTextMetrics, IDisposable')
replace('src/TextSpace.Skia/SkiaTextMetrics.cs', '    public void ClearMeasurements()\n    {\n', '    public long MetricsVersion { get; private set; }\n    public void ClearMeasurements()\n    {\n        MetricsVersion++;\n        foreach (var cachedShaper in _shapers.Values) cachedShaper.Dispose();\n        _shapers.Clear();\n')
replace('src/TextSpace.Skia/DocumentRenderer.cs', '    public DocumentLayout Layout(DocumentModel document) => new PageLayoutEngine(Metrics).Layout(document);', '    private PageLayoutEngine? _layoutEngine;\n    public DocumentLayout Layout(DocumentModel document) => (_layoutEngine ??= new PageLayoutEngine(Metrics)).Layout(document);')
replace('src/TextSpace.Layout/LayoutModels.cs', 'public sealed class DocumentLayout\n', 'public sealed partial class DocumentLayout\n')
replace('src/TextSpace.Layout/LayoutModels.cs', 'Height = top - PageGap; _lines = pages.SelectMany(p => p.Lines).ToArray();', 'Height = top - PageGap; _lines = pages.SelectMany(p => p.Lines).ToArray();\n        BuildTextLookup();')
replace('src/TextSpace.Layout/LayoutModels.cs', 'var line = _lines.LastOrDefault(l => position >= l.Start && position <= l.End) ?? _lines.LastOrDefault();', 'var line = FindCaretLine(position);')
replace('src/TextSpace.Layout/LayoutModels.cs', 'var line = page.Lines.OrderBy(l => (y < l.Y ? l.Y - y : y > l.Y + l.Height ? y - l.Y - l.Height : 0) * 10000\n            + (x < l.X ? l.X - x : x > l.X + l.Width ? x - l.X - l.Width : 0)).FirstOrDefault();', 'var line = NearestLine(page.Lines, x, y);')
replace('src/TextSpace.Skia/DocumentRenderer.cs', '    public byte[] ExportPng(DocumentModel document, int pageIndex = 0, double scale = 2)\n    {\n        var layout = Layout(document); pageIndex = Math.Clamp(pageIndex, 0, layout.Pages.Count - 1);', '    public byte[] ExportPng(DocumentModel document, int pageIndex = 0, double scale = 2) => ExportPng(document, Layout(document), pageIndex, scale);\n\n    /// <summary>Exports an existing layout snapshot. The caller supplies the corresponding document state.</summary>\n    public byte[] ExportPng(DocumentModel document, DocumentLayout layout, int pageIndex = 0, double scale = 2)\n    {\n        ArgumentNullException.ThrowIfNull(document); ArgumentNullException.ThrowIfNull(layout);\n        pageIndex = Math.Clamp(pageIndex, 0, layout.Pages.Count - 1);')
replace('src/TextSpace.Workbench/WordWorkbench.Files.cs', 'Surface.Renderer.ExportPng(Session.Document, Surface.Layout.Caret(Session.Selection.Active).PageIndex)', 'Surface.Renderer.ExportPng(Session.Document, Surface.Layout, Surface.Layout.Caret(Session.Selection.Active).PageIndex)')
replace('src/TextSpace.Workbench/WordWorkbench.Files.cs', 'Surface.Renderer.ExportPng(Session.Document, i, 1.5)', 'Surface.Renderer.ExportPng(Session.Document, Surface.Layout, i, 1.5)')
replace('src/TextSpace.Layout/LayoutModels.cs', '    public double Position(int offset) =>', '    private int[]? _boundaries;\n    internal ReadOnlySpan<int> CaretOffsets\n    {\n        get\n        {\n            if (_boundaries is not null) return _boundaries;\n            var offsets = System.Globalization.StringInfo.ParseCombiningCharacters(Text);\n            _boundaries = new int[offsets.Length + 1];\n            offsets.CopyTo(_boundaries, 0); _boundaries[^1] = Text.Length;\n            return _boundaries;\n        }\n    }\n    public double Position(int offset) =>')
replace('src/TextSpace.Layout/LayoutModels.cs', '        var chunk = Chunks.LastOrDefault(c => position >= c.Start && position <= c.End) ?? (position < Start ? Chunks[0] : Chunks[^1]);\n        return chunk.Position(position - chunk.Start);', '        for (var i = Chunks.Count - 1; i >= 0; i--)\n        {\n            var candidate = Chunks[i];\n            if (position >= candidate.Start && position <= candidate.End) return candidate.Position(position - candidate.Start);\n        }\n        var chunk = position < Start ? Chunks[0] : Chunks[^1];\n        return chunk.Position(position - chunk.Start);')
replace('src/TextSpace.Layout/LayoutModels.cs', '            var boundaries = System.Globalization.StringInfo.ParseCombiningCharacters(chunk.Text).Append(chunk.Text.Length);\n            foreach (var offset in boundaries)', '            foreach (var offset in chunk.CaretOffsets)')
replace('src/TextSpace.Skia/DocumentRenderer.cs', 'public void Dispose() { ClearImages(); Metrics.Dispose(); }', 'public void Dispose() { ClearImages(); _layoutEngine?.ParagraphCache.Clear(); Metrics.Dispose(); }')
